### ISSUE TITLE
DRY don't repeat yourself

### ISSUE THREAD

**Issue by erwinhenraat** [erwinhenraat/PythonExamples#1]
In callme.py

def callMe(name, number):
    print("&: Hello?")
    time.sleep(1)
    print("&: Who's there?")
    time.sleep(1)
    print("#: It's me "+ name)
    time.sleep(1)
    print("&:Hi "+ name+ " i'm sorry i'm busy right now can i call you back?")
    time.sleep(1)
    print("#: sure thing.")
    time.sleep(1)
    print("&: What's your number?")
    time.sleep(1)
    print("#it's "+number)
    time.sleep(1)
    print("&: Got it! call you later, Bye!")
    time.sleep(1)
    print("#: Bye!")
    time.sleep(1)
    print("click...")

callMe(sys.argv[1], sys.argv[2])

Dit kan veel compacter en minder herhalend zodat de code beter herbruikbaar wordt:

def callMe(name, number, text, waitTime):
    print(text)
    time.sleep(waitTime)

callMe("erwin", "0633706470", "&: Hello?" , 1)

**Comment by SilvanDomino** [comment]
Je kan ook de opmaak van de code netter maken.

**Comment by erwinhenraat** [comment]
Ja ik snap het maar er is nu geen tijd om dit te fixen het is ook niet superbelangrijk

**Comment by erwinhenraat** [comment]
Ik begrijp het probleem niet helemaal. Zou je nog meer uitleg willen geven

**Comment by SilvanDomino** [comment]
```python
def callMe(name, number, text, waitTime):
  print(text)
  time.sleep(waitTime)
```

**Comment by erwinhenraat** [comment]
`def callMe(name, number):
print("&: Hello?")
time.sleep(1)
print("&: Who's there?")
time.sleep(1)
print("#: It's me "+ name)
time.sleep(1)
print("&:Hi "+ name+ " i'm sorry i'm busy right now can i call you back?")
time.sleep(1)
print("#: sure thing.")
time.sleep(1)
print("&: What's your number?")
time.sleep(1)
print("#it's "+number)
time.sleep(1)
print("&: Got it! call you later, Bye!")
time.sleep(1)
print("#: Bye!")
time.sleep(1)
print("click...")

callMe(sys.argv[1], sys.argv[2])`

**Comment by erwinhenraat** [comment]
```def callMe(name, number):
print("&: Hello?")
time.sleep(1)
print("&: Who's there?")
time.sleep(1)
print("#: It's me "+ name)
time.sleep(1)
print("&:Hi "+ name+ " i'm sorry i'm busy right now can i call you back?")
time.sleep(1)
print("#: sure thing.")
time.sleep(1)
print("&: What's your number?")
time.sleep(1)
print("#it's "+number)
time.sleep(1)
print("&: Got it! call you later, Bye!")
time.sleep(1)
print("#: Bye!")
time.sleep(1)
print("click...")

callMe(sys.argv[1], sys.argv[2])
